name: chat_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_chat_ui: ^1.6.12
  random_avatar: ^0.0.8
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  open_filex: ^4.4.0
  uuid: ^4.3.3

  flutter_chat_types: any
  http: any
  mime: any
  path_provider: any
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - images/

